[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "plate-library"
version = "1.16.0"
description = "Maintenance UI for a simple microscopy plate library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit==1.55.0",
    "datasette==0.65.2",
    "pandas==2.3.3",
    "openpyxl==3.1.5",
    "yoyo-migrations==9.0.0",
    "pyproj==3.7.2",
    "mgrs==1.5.4",
    "folium==0.20.0",
    "streamlit-folium==0.27.1",
]

[project.optional-dependencies]
dev = [
    "pytest==3.7.2",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
plate_library = ["queries/*.sql", "queries/**/*.sql"]
